class Token:
    # Estereótipos de classe
    EVENT = 'EVENT'
    SITUATION = 'SITUATION'
    PROCESS = 'PROCESS'
    CATEGORY = 'CATEGORY'
    MIXIN = 'MIXIN'
    PHASE_MIXIN = 'PHASE_MIXIN'
    ROLE_MIXIN = 'ROLE_MIXIN'
    HISTORICAL_ROLE_MIXIN = 'HISTORICAL_ROLE_MIXIN'
    KIND = 'KIND'
    COLLECTIVE = 'COLLECTIVE'
    QUANTITY = 'QUANTITY'
    QUALITY = 'QUALITY'
    MODE = 'MODE'
    INTRINSIC_MODE = 'INTRINSIC_MODE'
    EXTRINSIC_MODE = 'EXTRINSIC_MODE'
    SUBCLASS_KIND = 'SUBCLASS_KIND'
    PHASE = 'PHASE'
    ROLE = 'ROLE'
    HISTORICAL_ROLE = 'HISTORICAL_ROLE'
    
    # Estereótipos de relações
    MATERIAL = 'MATERIAL'
    DERIVATION = 'DERIVATION'
    COMPARATIVE = 'COMPARATIVE'
    MEDIATION = 'MEDIATION'
    CHARACTERIZATION = 'CHARACTERIZATION'
    EXTERNAL_DEPENDENCE = 'EXTERNAL_DEPENDENCE'
    COMPONENT_OF = 'COMPONENT_OF'
    MEMBER_OF = 'MEMBER_OF'
    SUBCOLLECTION_OF = 'SUBCOLLECTION_OF'
    SUBQUALITY_OF = 'SUBQUALITY_OF'
    INSTANTIATION = 'INSTANTIATION'
    TERMINATION = 'TERMINATION'
    PARTICIPATIONAL = 'PARTICIPATIONAL'
    PARTICIPATION = 'PARTICIPATION'
    HISTORICAL_DEPENDENCE = 'HISTORICAL_DEPENDENCE'
    CREATION = 'CREATION'
    MANIFESTATION = 'MANIFESTATION'
    BRINGS_ABOUT = 'BRINGS_ABOUT'
    TRIGGERS = 'TRIGGERS'
    COMPOSITION = 'COMPOSITION'
    AGGREGATION = 'AGGREGATION'
    INHERENCE = 'INHERENCE'
    VALUE = 'VALUE'
    FORMAL = 'FORMAL'
    CONSTITUTION = 'CONSTITUTION'
    
    # Palavras reservadas
    GENSET = 'GENSET'
    DISJOINT = 'DISJOINT'
    COMPLETE = 'COMPLETE'
    GENERAL = 'GENERAL'
    SPECIFICS = 'SPECIFICS'
    WHERE = 'WHERE'
    PACKAGE = 'PACKAGE'
    
    # Tipos de dados
    NUMBER_TYPE = 'NUMBER_TYPE'
    STRING_TYPE = 'STRING_TYPE'
    BOOLEAN_TYPE = 'BOOLEAN_TYPE'
    DATE_TYPE = 'DATE_TYPE'
    TIME_TYPE = 'TIME_TYPE'
    DATETIME_TYPE = 'DATETIME_TYPE'
    
    # Meta-atributos
    ORDERED = 'ORDERED'
    CONST = 'CONST'
    DERIVED = 'DERIVED'
    SUBSETS = 'SUBSETS'
    REDEFINES = 'REDEFINES'
    
    # Identificadores
    CLASS_NAME = 'CLASS_NAME'
    RELATION_NAME = 'RELATION_NAME'
    INSTANCE_NAME = 'INSTANCE_NAME'
    DATATYPE_NAME = 'DATATYPE_NAME'
    ID = 'ID'
    NUMBER = 'NUMBER'
    STRING = 'STRING'
    
    # Símbolos
    LBRACE = 'LBRACE' # {
    RBRACE = 'RBRACE' # }
    LPAREN = 'LPAREN' # (
    RPAREN = 'RPAREN' # )
    LBRACKET = 'LBRACKET' # [
    RBRACKET = 'RBRACKET' # ]
    DOUBLE_DOT = 'DOUBLE_DOT' # ..
    DIAMOND_LEFT = 'DIAMOND_LEFT' # <>--
    DIAMOND_RIGHT = 'DIAMOND_RIGHT' # --<>
    ASTERISK = 'ASTERISK' # *
    AT = 'AT' # @
    COLON = 'COLON' # :
