from .closeable_tab import CloseableTabWidget
from .code_editor import CodeEditor
from .file_tab import FileTab
from .file_tree import FileTreeWidget
from .statistics_widget import StatisticsWidget
from .token_details_table import TokenDetailsTable
from .token_table import TokenTable
from .error_table import ErrorTable
from .syntax_highlighter import SyntaxHighlighter
